# Generated by Django 4.1.1 on 2022-11-11 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
    ]
